### ISSUE TITLE
ランダムに動く場合に動くべき場所を選択するアルゴリズムの改良

### ISSUE THREAD

**Issue by kyad** [kyad/burger_war#12]
DQN.py  270,315行目付近で努力したが考え方から再考した方がよいかも。
学習した結果エージェントが座標を指定して動かすのだがフィールド外、障害物が邪魔で進めない（障害物の真後ろ等）、障害物座標の場合はその場でステイ
動かないのは戦略として有りだと思うが、今いる座標と同じ位置を指定した時のみ動かないを学習する方が望ましいと思う

action = self.getIndexAtMaxN(retTargetQs, 2+int(np.random.rand()*9))
action = self.generateRandomDestination()
ランダムに動く場合にどこに動くべきかが、現在ランダムで決定するようになっている。これだと学習が進まない気がする。
ルールベースでも良いので、良さそうな場所を探して入れてやる方が良いのではないか。
動けるところからランダムとかでも良い。

**Comment by kenkenjlab** [comment]
色々試してみましたが、random選択でpath planning できないgoalになった場合、/move_base/DWAPlannerROS/global_planトピックが出てこないことを利用して、random選択をやり直すという実装はいかがでしょうか？

- 現状
  1. self.client.send_goal_and_wait()で4秒強制打ち切り
    - 内部的にはsend_goal()してwait_for_result()で4秒間待機し、goalにたどり着いていない場合はcancel_goal()している
- 提案
  1. self.client.send_goal()
  1. self_wait_for_result()で1秒待っている間にglobal_planトピックが新規に1個でもpublishされるかチェック
  1. publishされていたら、更にself_wait_for_result()する。
  1. publishされていなければrandom選択をやり直す(iに戻る)

ところで、そもそもランダム選択ではなくpredict結果の場合でも、path planning が失敗してステイするパターンがあるように思います。
例えば目の前が壁の状態です。navigation_stackでは(旋回しながら)前進でたどり着くpath plannningをするので、一旦後退・その場で旋回などの特別対応をするか、または、行き止まりになってしまうgoal設定には罰を与えるよう学習させて続行不能なgoalを指定しなくするのがよいと思いますがいかがでしょうか。ルールベースを避けるという方針的には後者でしょうか。

- predictの場合
  - path plan できないgoal指定時は罰を与える
- randomの場合
  - path plan できるgoalが出るまでrandom選択をやり直す

更に気になったのですが、現状4秒経過すると強制的に新しいgoalが設定されてしまいますが、意図通りでしょうか？
（path planが正しければ）指定したgoalには最後までたどり着かせた方がよいように思いますが、いかがでしょうか？

**Comment by kyad** [comment]
> 更に気になったのですが、現状4秒経過すると強制的に新しいgoalが設定されてしまいますが、意図通りでしょうか？
そのgoalがベストであれば、理想的には4秒後も同じgoalを設定するはず。良くなければ4秒後に違うgoalを設定するはず。意図通り

**Comment by kenkenjlab** [comment]
実装しました
8f09019e679114f6d809a838839e1139da030dc9

**Comment by kyad** [comment]
> [ERR] Invalid goal is set by prediction (または random selection). Retrying...（赤字）

@kenkenjlab さん、今rospy.logerrやrospy.logwarnで実装されているログは正常系だと思いますので、rospy.loginfo([INFO])に変更しても良いでしょうか？
異常系のログをlogerr, logwarnで表示しようかなと思っておりまして、正常系と異常系を区別するために変更したいと思っています。

**Comment by kyad** [comment]
rospy.loginfoに変更してOK。logerrは学習を止めないといけないようなクリティカルなログに使いたい。
