### ISSUE TITLE
環境でred/blueのnamespaceが消えているのに対応しているか確認する

### ISSUE THREAD

**Issue by kyad** [kyad/burger_war#14]
このcommitで red/blueのnamespaceが消えてそうにみえます
https://github.com/seigot/burger_war/commit/f4a04247371adf0a76843d9c8a2632d58fda3e68
色々起動してから、rostopic list 実行で利用可能なトピック一覧を表示できます
どうやって自分はred/blueを区別するようにしているのか、運営に確認。

**Comment by az999x** [comment]
今、enemyと空になってるように見えますね。

**Comment by kyad** [comment]
環境でred/blueのnamespaceは消えていて、開発する上では自分がredかblueかは意識せずに開発してくださいというのが基本だそうです。

我々の場合は、redが学習する側、blueが学習の相方という役割にしており、redとblueを区別したいという事情があるため、burger_war/burger_war/launch/your_burger.launch でredかblueかをrosのパラメータで与えてredかblueかを知らせるようにしています。この方針は、これはこれで良いと思います。

一応、自分がredかblueかのパラメータが与えずにlaunchするのがデフォルトということなので、このようなlaunchの場合は自分がredになるように修正しようと思います。

**Comment by kyad** [comment]
ca68a48c4384bf55f8f0e4371922b825d8b8b198

**Comment by az999x** [comment]
横からすみません。slackでも横からすみません。red（自機）とblue（敵機）はどっちもTeamEmbeddesAI.pyを起動するって事ですね？
fileのread/writeのケアが必要かも。エラーチェックと共に必要なbyte数読めたか/書けたかどうかとか（どこまで出来るか分からんけど）。同じファイルにアクセスしないならなくてもいいですが。

以上お節介でした

**Comment by kyad** [comment]
はい、redもblueもTeamEmbeddedAI.pyを起動するようにしています。同じhdf5ファイルに対してredは書き込み、blueは読み込みをするので、読み書きが同時に起こる可能性をケアしないといけません。
書き込み(red)
https://github.com/keras-team/keras/blob/2.2.5/keras/engine/network.py#L1142
読み込み(blue)
https://github.com/keras-team/keras/blob/2.2.5/keras/engine/network.py#L1175
→https://github.com/keras-team/keras/blob/2.2.5/keras/engine/saving.py#L1202
読み込み側のload_weights_from_hdf5_group_by_nameは、モデルと、読み込んだhdf5の構造が異なると例外を上げるようになっているので、万一読み書きタイミングが重なって変なデータを読んでしまったら、エラーで止まることになると思います。

**Comment by az999x** [comment]
ごめんなさい。参照先読めて無いですが、例外あがったらリトライ希望します。例外あがっても次の瞬間は読めるはずなので。そこで学習終わるのもったいないなぁと

**Comment by kyad** [comment]
リトライ良いですね！別のissueで上げたいと思います。
