### ISSUE TITLE
位置情報がスパースなのを改良

### ISSUE THREAD

**Issue by kyad** [kyad/burger_war#15]
- （自己と相手の）位置情報が16x16matrix中の1x1でスパースすぎる（情報量が削られ過ぎている）。位置情報だけでなく、入力層が全体的にスパースなのでCNNを使うメリットがない気がする。
  - 16×16の行列に１セルだけ１を立てて後は全部ゼロって事で有効活用出来てないって事ですね。確かにそう思います。最初は角度も一緒に入れようかなと思ったのですが、上手い方法が思いつかず別チャンネルに分けちゃいました。
  - ちょっと割引率を掛けて数ステップ前の座標を入れるとかでも面白いかもしれませんね。(1ステップ前は0.8で２ステップ前は0.6を入れるとか)
    - これ凄く良いと思います。やはり16x16行列中の１セルだけだと情報量がなさすぎて位置情報があまり意味をなさない気がします。

- 連続値を扱えるというDQNのメリットを活かせない。

→ 「過去のやつを取り入れる」を入れてみる

**Comment by Yoshihama0901** [comment]
減衰係数決め打ち(0.5)ですが、過去の座標を参照するようにしました。

**Comment by kyad** [comment]
9cef81379f9b9629c6a0d6ee7e9e1f49981b192b
