### ISSUE TITLE
開始してから最初の動作まで10秒以上かかる

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#18]
Step.1: 11.1[s]
　　Step.2: 17.1[s]
　　Step.3: 23.1[s]
　　Step.4: 26.2[s]
　　Step.5: 32.2[s]
　　Step.6: 35.2[s]
　　Step.6: 41.2[s]
　最初の位置が設定されるのに試合開始11[s]経過している。
　以降3[s]間隔だけど、6[s]間隔になってたりする。

**Comment by Yoshihama0901** [comment]
最初の２stepくらいは決め打ちで動作を行って、
その間に並列処理で読み込む

**Comment by Yoshihama0901** [comment]
最初の時間を計測しました。
　DNNモデル読み込みに約５[s]
　重み読み込みに約2[s]
程度掛かってました。取り敢えずこれの削減を目指します。

**Comment by Yoshihama0901** [comment]
初手と２手目を固定しました。(後で変更可)
一旦以下です。
 1st step : 座標(-0.3, 0)狙いで、(6,9)
 2nd step : 座標(0, 0.6)狙いで、(10,10)
10[s]程度かけて座標(0, 0.6)辺りに移動して、Field Scoreを２点取るようにしたつもりです。

**Comment by kyad** [comment]
f9b4a241fbc7613c03388e5e89d9f3f4e843a266

**Comment by Yoshihama0901** [comment]
モデル読み込みを並列でするようにしたんですが、エラーが出てしまいます…。
一旦直せないのコメントアウト（477行目辺り）

**Comment by kyad** [comment]
63c812598153d5b1f1717ee78403736ba32ed89c
98300a0438a37dd7333567f83614a849bcbcdd8b

**Comment by kyad** [comment]
並列化をうまく実装できる人募集中。

**Comment by Yoshihama0901** [comment]
DNN Modelを変更したら(ResNet)初手がますます遅くなってしまいました。
動き出すのに23[s]くらい掛かってます。

**Comment by Yoshihama0901** [comment]
>Kerasはスレッドセーフでないからです。（バグ）
だそうです。難しい…。ここにヒントありました。
https://teratail.com/questions/117352

まだ途中ですけど初手の高速化出来そうです。
とりあえず途中段階ですが、commit してます。

**Comment by Yoshihama0901** [comment]
試合始まってからすぐシャカシャカ動くように変更出来ました。
決め打ちですが、どのように動かすかはこれから調整します。
