### ISSUE TITLE
リセット動作が不安定

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#19]
リセット動作がイマイチちゃんと動いていないように感じます。
高確率で審判と敵機が落ちる感じです。学習できない...。

1/2回程度の頻度でエラー出てます。Dockerです。
違ったりするんですか？？困る...。
エラーメッセージを記載させて頂きます。(Dockerからのテキストのペーストが出来ないので努力コピー)[enemy_bot/send_id_to_judge-12] process had died [pid 23347, exit code 1, cmd /home/ubuntu/catlin_ws/src/burger_war/buger_war/script/sendIdToJudge.py name:=send_id_to_judge log:==/moge/ubuntu/.ros/log/fd5c7d96-d7dc-llea-a039-0242ac110002/enemybot-sendin_to_judge-12.log].[send_id_to_judge-7] process had died [pid 25803, exit code 1, cmd /home/ubuntu/catlin_ws/src/burger_war/buger_war/script/sendIdToJudge.py name:=send_id_to_judge log:==/moge/ubuntu/.ros/log/fd5c7d96-d7dc-llea-a039-0242ac110002/enemybot-sendin_to_judge-7.log].

→ 20_resetブランチで直っているか確認

**Comment by Yoshihama0901** [comment]
2020/08/09 14:05 に確認したんですけど同じエラーになってしまいました。
上記エラーログになります。

> enemybot-sendin_to_judge-12.log
...前略
File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
AttributeError: 'NoneType' object has no attribute 'getsockname'

**Comment by kyad** [comment]
de1a732bb5e1ea73b8c1c61b093090f53f8f6fca
e03a23dc92e8bf2a8d0f8deecaa661d2d879adc2

**Comment by az999x** [comment]
なるほど、修正コミットを書けばいいんですね。そういやみんな書いてますね。
