### ISSUE TITLE
シミュレーションの高速化設定方法

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#20]
時間分解能が減っても良いので、早くシミュレーションが進むようにしたい。
例えば、
　real time ...  10倍
　max step ...  10倍
としたときにWARNINGがいっぱい出る。
rostopic pubで送る頻度を高めたらよい？

**Comment by az999x** [comment]
#6 に書いたけど、早く学習を回すにはreplayのfor文あたりを早くするのがめんどくさいけど効果ある。一方gazeboの方はreal time rateを0にすると、PCのご機嫌を伺いながら最大で動くようになる(ので、振れる)。私のPCで2.5-3.0ぐらい。順調に動く。

今はアホほどファンが回ってreal time factorが2.5以下で動いてて、あまり良くないのか死ぬほどWARNINGでる。

**Comment by kyad** [comment]
#24 （審判サーバーからcallback_war_stateで取得しているtimeの値は実時間なので、シミュレーション時間を取得できていない）を考慮する必要があります。

**Comment by az999x** [comment]
いい案があったら教えてください
わかってることは

- gazeboをサクサク回すためにはロボットのコードも負けないぐらいサクサク回さないといけない
- gazeboのrealtimerateをあげるとロボットのコードが一周する速度がなぜか落ちる（10%から20%ぐらい？）PCのスペックの問題かもしれない
- WARNINGを見てるとなんか期待してるメッセージ（かなんか）を10hzで送れ、お前は0.24secで送ってる、って言われてる気がしてる。1周2sec程かかってるのにそんなものあるのか？（メッセージの内容覚えてないので何言ってるのかわからないと思いますが）

理想は
- 分解能を犠牲にせずとgazebo高速化を両立）でも学習時間がかかるのでどこまで伸ばせるか分からない）
    そのためにはボトルネックを取らないといけない
    案としては（どれぐらい効くか分かりませんが
       replayを改善（ここが一番かかってる）
       変数を型宣言する
       型宣言した後でコードを分けてcythonでビルド（ビルドしちゃうとカットアンドトライしにくくなるけど、あと知識があんまりない）
       みんなgpuつむw（学習時間も結構かかってる）
          さくっとやってみたけど怒られました。私のcuda環境に問題があるかも
     ま、昨日一旦全部諦めたわけですが…
- gazebo高速化だけやって相対的な時間分解能向上は諦める
     WARNINGメッセージの仰せられるとおりちゃんと対応する。10hzで応答できるようにする
     まずちゃんとWARNING見ないとね
     rosparamで設定したら終わりかもしれないし（当たりをつけてしてみたりはしたけど）
     けど、例えば倍速でgazebo動かしても1分半分の学習量だとあんま嬉しくないこと無い？推論も1分半分しかしないし。（★ここ認識あってます？）


てな感じです。
今日は不貞寝をしてました。

スマホで書いたのでスペースの関係で読みにくくなってたらごめんなさい

晩飯調達します

**Comment by kyad** [comment]
replayをnumpy化して高速化するとbatch_size(40)倍速くなる？

Real Time Factorを2~3倍にするぐらいで留める。
GazeboからGazebo時間を取ってこれるなら、それも考慮して学習終了時間を設定してやる
できないなら、適当に試合終了時間を2~3倍にする、でも良い。

**Comment by kyad** [comment]
f3ba5849da05a24af5d0b9b069a339a28f6886da
Gazeboからreal time factorを取ってくるのは諦め、手動でreal time factorをセットしてもらうことにしました。
real time factorをTeamEmbeddedAI.pyのrealTimeFactor変数に指定すると、それを考慮してシミュレーション終了時間を設定します。
