### ISSUE TITLE
試合時の設定

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#23]
学習モードじゃない場合の設定を調整しないと
　444行目の重みの読み込みが、試合時に別の場所から読んでるのなんでだっけ？

**Comment by kyad** [comment]
train=Falseにしたときの挙動を一応確認しておくこと。

**Comment by kyad** [comment]
試合時は、TeamEmbeddedAI.pyのSim_flag = Falseに指定すれば良い。
729da6c7678bae6f4c290e95f6dcc81aff359766
