### ISSUE TITLE
timeがシミュレーション時間と一致しない問題

### ISSUE THREAD

**Issue by kenjirotorii** [kyad/burger_war#24]
審判サーバーからcallback_war_stateで取得しているtimeの値は実時間なので、シミュレーション時間を取得できていない。real time factorが小さいと本来３分間の試合が数十秒で終了してしまう。rospy.Time.now()とかで取得できる？

**Comment by az999x** [comment]
シミュレーション時間は取れてないですね。多分。けど、real time factorが2-3ぐらいを行き来してて、設定した30秒(ちょい超え)で試合は終わる。そこは実時間なんで。real time factorが2で3分間分学習したかったら、TimeLimitを90にしないといけない？とかかな。gazeboとrosの周波数を一致させればrospyのメソッドで取れるかもしれない。

**Comment by kyad** [comment]
Duplicate of #20
