### ISSUE TITLE
memoryのresetが有効になっていない

### ISSUE THREAD

**Issue by kenjirotorii** [kyad/burger_war#25]
restartするときにmemory.reset()でメモリをリセットしているように見えるが、DQN.pyの方ではただのpassになっている。
https://github.com/kyad/burger_war/blob/master/burger_war/scripts/MyModule/DQN.py#L245

つまり、現状では複数エピソードを行う場合には過去のエピソードのデータも学習に使用している。局所解に入らないようにするためにこういう仕様にしている？

**Comment by Yoshihama0901** [comment]
ご指摘ありがとうございます。最も自信がない部分になります。
DQN.py 190行目のreplay()関数が合っているのか見て頂けると有り難いです。

理解としては、214行目でreward=0の時は前の状態から割引率を掛けてrewardを貰っているて
±1の場合はそのまま報酬が入るので、くっつけても分離している理解でおります。
その他、replay()関数が合っているが見て頂けると非常に有り難いです。

**Comment by kenjirotorii** [comment]
コメントありがとうございます。以下、改めて考えた結果です。

- 分離しているとは、エピソードごとに区別がつくということでしょうか？僕の認識だとmemoryに保存されているのは経験(state, action, next_state, reward)だけであって、ランダムで抽出した学習データがどのエピソードから得られたかはわからないと思います。あくまで「ある状態stateである行動actionを取った結果、次の状態next_stateに移り、報酬rewardが得られた」という経験を蓄積していくという理解です。なので、memoryへのデータの保存は、エピソードをまたいでも問題ないと思いました。

- DQNのネットワークの学習について少し疑問点があります。本来DQNの学習では、過去のモデルtargetQN、今得られた報酬r、次の状態s'により教師データを計算し、今の状態と行動(s, a)に対応するQ値をその教師データに近づけるように重みを更新します。**つまり、16x16x1のshapeで出力されるQ値のうち1セルのみに着目した重み更新です。**しかし、model.fit(input, target)ではその他の関係ない(s, a)を含んで全体で重みを更新しています。長い目で見ると結果は大きく変わらない気はしますが、どうでしょうか？

**Comment by Yoshihama0901** [comment]
> ・分離しているとは…
同じ理解です。

> ・DQNのネットワーク…
まさにreplay()関数の中身そのものの疑問になります。
そうですね、私も完全には理解していないので間違っているかもしれません。
DQN.py の216行目で今の学習結果から16×16を取り出して、
228行目で１セルのみ情報を更新して正解データとして学習させてる感じになってます。
って何かを答えた感じになりました？

**Comment by kenjirotorii** [comment]
model.fitでmodelが更新されるので、(a)教師データ(16x16)の中でターゲットとなるセル以外のセルも考慮して重みを更新すること、(b)ターゲットのセルのみ（つまりスカラー同士）だけで重みを更新すること、が一致するかが疑問でした。(a)では16x16の出力と16x16の教師データを近づける。(b)では16x16のうちその時の行動に一致する１セル（スカラー）について出力と教師データを近づける。

**Comment by kyad** [comment]
memoryのresetが有効になっていない →上の議論より、そのままreset無しで良い。
16x16x1のshapeで出力されるQ値のうち1セルのみに着目した重み更新→別issueで上げます。
