### ISSUE TITLE
障害物で動けない場所を指定すると動けない

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#28]
ただでさえ座標を離散化して動ける場所を制約している上に、動けない場所があるので
動ける近い場所に変換するようにしませんか？

**Comment by kyad** [comment]
例えば3,3に障害物があったとして、3,3の中でも障害物がない場所を返すようにする。

**Comment by kenkenjlab** [comment]
障害物で到達できないactionは書き換えるよう修正しました。
併せて壁ぎりぎりも到達できないように見えたので、壁用の書き換えも実装しました。
2d9a90b429a34273503f7f367c22dd85cd29af06
