### ISSUE TITLE
ランダムの範囲

### ISSUE THREAD

**Issue by Yoshihama0901** [kyad/burger_war#36]
DQN.py 158行目
1～14の範囲になってます。
0～15の範囲にしますか？

**Comment by kyad** [comment]
昨年、なぜ1～14にしたんでしたっけ...？
私も覚えていないので、特に理由が無ければ0～15にして、もし動きがおかしくなれば1～14に戻す、でどうでしょうか？
（0や15が当たった場合、フィールドの壁に引っかかって動きがおかしくなりそうな気もします）

**Comment by Yoshihama0901** [comment]
昨年はフィールドのサイズが適当で端っこまで移動出来なかったので、
端を選択肢から除いてました。今年はフィールドサイズをちゃんとしたので、
戦略上必要なのであれば端を活用してもいいのかなと思ってます。

**Comment by kyad** [comment]
変更しましょう。

**Comment by Yoshihama0901** [comment]
変更しました

**Comment by kyad** [comment]
1ece9df7e18245e3c97e9c114782b5fbf0055e3d
