### ISSUE TITLE
targetQNは必要ないのでは

### ISSUE THREAD

**Issue by kenjirotorii** [kyad/burger_war#37]
TeamEmbeddedAI.pyでmainQNの他に教師データを作るのに必要なtargetQNを作っているが、NWの作成や重みのコピーには時間がかかるのでtargetQNをなくして初動までにかかる時間を短縮したい。教師データを作る際には更新する前のモデルを使えばよく、targetQNは必要ない。

**Comment by kyad** [comment]
targetQNはDDQNをするためだけに残しているので、DDQNをやらないという判断をすれば、targetQNは消せますね。
DDQNにするとモデルファイルを2つ読みこまないといけなくなり、さらに遅くなりますし、DDQNやめようかな…？（悩み中です）

**Comment by kenjirotorii** [comment]
DDQNを使う想定だったのですね。現状のコードだとエピソードごと（DDQN）ではなく、ステップごと（DQN）にtargetQNをmainQNで更新しているので消せますね。

**Comment by kenjirotorii** [comment]
8957b265e08c91973ac61c692608ea877d3d5465
学習を試合後にまとめて行う仕様にするときにDDQNっぽくしました。targetQNには一試合前のモデルを使うことになります。

**Comment by kyad** [comment]
DDQN(mainQNとtargetQNを分ける)は、報酬を理解するモデルと、行動を決めるモデルを分ける。
DDQNはモデルが増えて更に遅くなるので、DQN前提にする。targetQNは消してコードを軽くする。
合わせて、targetQNには一試合前のモデルを使うのではなく、最新の試合のモデルを使うように変更する。

**Comment by kenjirotorii** [comment]
71bdcda76338cbe1422254e89718fd7cb64f1313
