### ISSUE TITLE
学習時間の刻み幅が粗い

### ISSUE THREAD

**Issue by kyad** [kyad/burger_war#6]
TeamEmbeddedAI.py  ３秒毎くらいで判断してなかったかなぁ？　１秒刻みくらいにしたい
動けなかった場合に、3秒だと長い。1秒で動きたい。
self.client.send_goal_and_wait(goal, execute_timeout=rospy.Duration(4))を短くする？
https://github.com/kyad/burger_war/blob/master/burger_war/scripts/TeamEmbeddedAI.py#L388
短くした分だけ、batch_size = 40 を増やすこと。
https://github.com/kyad/burger_war/blob/master/burger_war/scripts/TeamEmbeddedAI.py#L337
入れすぎると推論に時間がかかる。

**Comment by kenjirotorii** [comment]
- MoveBaseGoalを使う場合、設定したgoalに到達するかexecute_timeoutで指定した時間経たないと次の処理(step)に進まない。基本的にgoalに到達することは稀なので、execute_timeoutの時間が学習の時間刻みとなる。
- 学習はmemoryにbatch_size(40)以上のデータが保存されていないと行われない。時間刻みを４秒に設定すると１エピソードが180 (sec) / 4 (sec/step) = 45 stepとなるので40 step目以降でしか学習が行われない。一方で、時間刻みを小さくし過ぎると40step以降、毎ステップで学習するので効率が悪い。

**Comment by az999x** [comment]
学習時間はrospy.Duration(n)に設定するnに依存するのかね。0.1とか設定して回してると1周回るのが1.8secぐらい。支配的なのはreplay処理。学習に0.5sec、その上のfor文で1sec。あとはsetGoalが0.2secぐらい。DQN.pyをcythonでshared libraryにしてみたけどあんまり変わらない。地道にreplayをcython対応すれば1secいないで1周する気がする。あ、batch_size変えてない。

**Comment by kenjirotorii** [comment]
学習に時間がかかることを考慮してませんでした。僕もn=1とかで回したんですけどrealtimefactorが小さすぎてデータ数がbatch_sizeを超える前に試合が終わっていたので学習時間は見れませんでした...
バッチのfor文は無くせるはずなのでもう少し早くなるとは思います。

**Comment by kyad** [comment]
2秒待ちに変えてみましょう。
rospy.Duration(n)のnを短くしないと、シミュレーションを高速化できない(#20)。情報送ってくださいのWARNINGが出まくってしまう。
だからといってnを短くしすぎると、ころころgoalが変わるので、それはそれで困る。
rospy.Duration(4)の4と、r.sleep()は同期していて、この場合内部のループをどんだけ早くしてもr.sleepで4秒待ってしまう。

**Comment by kenjirotorii** [comment]
163d1dee36a39f2d9dcd72633b6a4f9822f46feb
