### ISSUE TITLE
得点を大きく表現したい

### ISSUE THREAD

**Issue by kyad** [kyad/burger_war#7]
TeamEmbeddedAI.py  91行目付近　もっと大きく着色しても良いかもと思ってました      (今の実装では、得点が入っている所を1にするのを1px×1pxだけにしているが、もっと大きくしても良いと思う)

**Comment by Yoshihama0901** [comment]
16倍の大きさで塗り潰す変更をしてます。

**Comment by kyad** [comment]
fe91aeb4cfcfc7fba9250592cb5f2caeaba1dd43
@Yoshihama0901 修正を確認しました。Tomato_S, Pudding_N, OctopusWiener_N, Omelette_Sが実際のマップ上の位置よりも外側に塗りつぶされているような気がするのですが、意図的にそうされているのでしょうか？

**Comment by kyad** [comment]
塗りつぶす位置は学習用なので、実際のマップ上の座標と必ずしも一致している必要は無いため、このような変更でOK。
